# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go generate ./...
    - gofmt -s -w .
    #    - golint $(go list ./... )
#    - go test ./...
#    - go test -coverprofile dist/main-cover.out ./...
#    - go tool cover -html=dist/main-cover.out -o coverage/index.html
#    - go tool cover -func=dist/main-cover.out -o coverage/coverage

builds:
  - main: ./cmd/go-template-engine/main.go
    binary: go-template-engine
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.VERSION={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    #      - openbsd
    #      - freebsd
    goarch:
      - amd64

archives:
  - id: main
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
#      darwin: Darwin
#      linux: Linux
#      windows: Windows

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  commit_author:
    name: marcelocorreia
    email: marcelo@correia.io

brews:
  - name: go-template-engine
    tap:
      owner: marcelocorreia
      name: homebrew-taps
      #token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/marcelocorreia/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: marcelocorreia
      email: marcelo@correia.io
    folder: Formula
    homepage: "https://github.com/marcelocorreia/go-template-engine"
    description: "Easy tool to apply Go Templates in BAU jobs"
    license: "NotSureYet"
    test: |
      system "#{bin}/go-template-engine --version"
    install: |
      bin.install "go-template-engine"


dockers:
  - image_templates:
    - marcelocorreia/go-template-engine
    skip_push: true