include env.mk pipeline.mk
merda:
	@echo "MERDA"
	@echo " MERDA"
	@echo "  MERDA"
	@echo "   MERDA"
	@echo "    MERDA"
	@echo "     MERDA"
	@echo "    MERDA"
	@echo "   MERDA"
	@echo "  MERDA"
	@echo " MERDA"
	@echo "MERDA"
	@echo "MERDA"
	@echo " MERDA"
	@echo "  MERDA"
	@echo "   MERDA"
	@echo "    MERDA"
	@echo "     MERDA"
	@echo "    MERDA"
	@echo "   MERDA"
	@echo "  MERDA"
	@echo " MERDA"
	@echo "MERDA"
	@echo "MERDA"
	@echo " MERDA"
	@echo "  MERDA"
	@echo "   MERDA"
	@echo "    MERDA"
	@echo "     MERDA"
	@echo "    MERDA"
	@echo "   MERDA"
	@echo "  MERDA"
	@echo " MERDA"
	@echo "MERDA"
	@echo "MERDA"
	@echo " MERDA"
	@echo "  MERDA"
	@echo "   MERDA"
	@echo "    MERDA"
	@echo "     MERDA"
	@echo "    MERDA"
	@echo "   MERDA"
	@echo "  MERDA"
	@echo " MERDA"
	@echo "MERDA"

