platform: linux

inputs:
  - name: go_repo
    path: .

image_resource:
  type: docker-image
  source:
    repository: marcelocorreia/go-glide-builder
    tag: 'latest'

run:
  path: make
  args: [package]