---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: marcelocorreia/go-glide-builder
    tag: 'latest'

inputs:
- name: go_repo

outputs:
- name: dist

run:
  path: go_repo/make.sh
  args: [package]