---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: resource-tutorial
  - task: create-some-files
    file: resource-tutorial/cicd/create_some_files.yml
  - task: show-some-files
    file: resource-tutorial/cicd/show_files.yml
