resources:
  - name: go_repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
  - name: build
    serial: true
    plan:
      - get: go_repo
        trigger: true
      - task: build
        config:
          platform: linux
          inputs:
            - name: go_repo
              path: .
          image_resource:
            type: docker-image
            source:
              repository: marcelocorreia/go-glide-builder
              tag: 'latest'
          run:
            path: make package


