#
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

#
resources:
  - name: gte-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: gte-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

  - name: s3
    type: s3
    source:
      bucket: mcpackages
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      region_name: ap-southeast-2
      regexp: go-template-engine/go-template-engine-(.*).tar.gz

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_webook}}

jobs:
  - name: integration
    serial: true
    public: true
    plan:
      - get: gte-repo-dev
        trigger: true
      - task: test
        file: gte-repo-dev/cicd/gte-test.yml
        on_success:
          task: integration
          file: gte-repo-dev/cicd/gte-build.yml
      - put: resource_version
        params:
          bump: patch
    on_failure:
      put: slack-alert
      params:
        channel: '#ci'
        icon_emoji: ':skull_and_crossbones:'
        text: |
          :bomb: $BUILD_PIPELINE_NAME
          Build $BUILD_NAME
          Job: *$BUILD_JOB_NAME*
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: release
    public: true
    serial: true
    plan:
    - get: gte-repo-master
      trigger: true
    - task: release
      file: gte-repo-master/cicd/gte-release.yml
    - put: resource_version
      params:
        bump: minor
    - put: github_release
      params:
        name: resource_version/version
        tag: resource_version/version
        body: gte-repo-master/README.md
        globs:
        - package/*gz
    - put: s3
      params:
        file: package/*.tar.gz
        acl: public-read
    on_failure:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          :warning: ($PIPELINE_NAME) -> (Build $BUILD_NAME). *$BUILD_JOB_NAME* failed!
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_success:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          :skull_and_crossbones: $BUILD_PIPELINE_NAME
          Build $BUILD_NAME
          Job: *$BUILD_JOB_NAME*
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
