---
resources:
  - name: go-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: go-repo
  - task: create-some-files
    file: go-repo/cicd/create_some_files.yml
  - task: show-some-files
    file: go-repo/cicd/show_files.yml
  - task: build
    file: go-repo/cicd/build.yml
  - task: release
    file: go-repo/cicd/release.yml
