---
resources:
  - name: go_repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
- name: package
  public: true
  plan:
  - get: go_repo
  - task: build
    file: go_repo/cicd/build.yml
  - task: release
    file: go_repo/cicd/release.yml
