resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: go-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: go-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

  - name: s3
    type: s3
    source:
      bucket: mcpackages
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      region_name: ap-southeast-2
      regexp: go-template-engine/go-template-engine-(.*).tar.gz

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_webook}}

jobs:
  - name: integration
    serial: true
    public: true
    plan:
    - get: go-repo-dev
      trigger: true
    - task: test
      file: go-repo-dev/cicd/go-test.yml
      on_success:
        task: integration
        file: go-repo-dev/cicd/go-build.yml
      on_failure:
        do:
        - put: slack-alert
            params:
                channel: '#project-ci'
                icon_emoji: ':concourse:'
                text: |
                :warning: Build $BUILD_NAME. *$BUILD_JOB_NAME* failed!
  - name: release
    public: true
    serial: true
    plan:
    - get: go-repo-master
      trigger: true
    - task: build
      file: go-repo-master/cicd/build-master.yml
    - put: resource_version
      params:
        bump: patch
    - put: github_release
      params:
        name: resource_version/version
        tag: resource_version/version
        globs:
        - package/*gz
    - put: s3
      params:
        file: package/*.tar.gz
        acl: public-read
    - put: slack-alert
      params:
        channel: '#ci'
        text: |
          {{git_repo}} has a new build. Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME