---
resources:
- name: go-repo
  type: git
  source:
    uri: {{git_repo_url}}
    branch: master
    private_key: {{git_private_key}}
    username: {{github_user}}

jobs:
- name: go-template-engine
  public: true
  plan:
  - get: go-repo
  - task: build
    file: go-repo/cicd/create_some_files.yml
  - task: release
    file: go-repo/cicd/show_files.yml
