---
resources:
- name: go-repo
  type: git
  source:
    uri: {{git_repo_url}}
    branch: master
    private_key: {{git_private_key}}
    username: {{github_user}}

- name: resource_version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: {{git_repo_url}}
    branch: version
    file: version
    private_key: {{git_private_key}}
    username: {{github_user}}

jobs:
- name: go-template-engine
  public: true
  plan:
  - get: go-repo
    trigger: true
  - put: resource_version
    params:
      bump: patch
  - task: build
    file: go-repo/cicd/build.yml
  - task: release
    file: go-repo/cicd/release.yml
  - put: resource_version
    params:
      file: resource_version/version

