---
resources:
  - name: git-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: resource-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: github-release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo_name}}
      access_token: {{github_token}}
jobs:
  - name: release
    serial: true
    public: true
    plan:
      - get: resource-version
        params:
          bump: patch

      - get: git-repo-master
        trigger: true

      - task: ci
        file: git-repo-master/ci/release.yml
        params:
          MAKE_TARGETS: _prepare _release

      - put: github-release
        params:
          name: resource-version/version
          tag: resource-version/version
          body: git-repo-master/README.md
          globs:
              - git-repo-master/dist/*tar.gz

