---
resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: git-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: github-release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo_name}}
      access_token: {{github_token}}

jobs:
  - name: integration
    build_logs_to_retain: 10
    serial: true
    plan:
    - get: git-repo-dev
      trigger: true
    - task: ci
      file: git-repo-dev/ci/integration.yml
      params:
        MAKE_TARGETS: _prepare _test _build

  - name: release
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-master
        trigger: true

      - put: resource_version
        params:
          bump: minor

      - task: ci
        file: git-repo-master/ci/release.yml
        params:
          MAKE_TARGETS: _prepare deps _release
          VERSION: resource_version

      - put: github-release
        params:
          name: resource_version/version
          tag: resource_version/version
          globs:
              - output/*tar.gz

