---
resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: git-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: git-repo-homebrew
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: app-resource-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: app-github-release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo_name}}
      access_token: {{github_token}}

jobs:
  - name: integration
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-dev
        trigger: true

      - task: ci
        file: git-repo-dev/ci/integration.yml
        params:
          MAKE_TARGETS: _prepare _build

      - put: app-resource-version
        params:
          bump: patch

  - name: release
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-homebrew
      - get: git-repo-dev

      - get: git-repo-master
        trigger: true
        passed: ["integration"]

      - put: app-resource-version
        params:
          bump: minor

      - task: ci
        file: git-repo-master/ci/release.yml
        params:
          MAKE_TARGETS: _prepare deps _build _release

      - put: app-github-release
        params:
          name: app-resource-version/version
          tag: app-resource-version/version
          globs:
              - output/*zip

  - name: update-homebrew-tap
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-homebrew
        trigger: true
        passed: ["release"]
      - task: update
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: marcelocorreia/terraform
              tag: 'latest'
          inputs:
          - name: git-repo-homebrew
          run:
            path: make
            args: ["-C","git-repo-homebrew","update_all"]