---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: git-repo-dev
    type: git
    source:
      uri: {{git_repo_url}}
      branch: dev
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: app-resource-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: app-github-release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo_name}}
      access_token: {{github_token}}

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_webook}}

  - name: s3
    type: s3
    source:
      bucket: {{s3_bucket}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      region_name: ap-southeast-2
      regexp: (.*).zip

jobs:
  - name: integration
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-dev
        trigger: true
      - task: ci
        file: git-repo-dev/ci/integration.yml
        params:
          MAKE_TARGETS: _prepare _test _build
    on_failure:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          Build $BUILD_NAME. *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* failed!
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


  - name: release
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo-master
        trigger: true

      - put: app-resource-version
        params:
          bump: minor

      - task: ci
        file: git-repo-master/ci/release.yml
        params:
          MAKE_TARGETS: _prepare deps _release

      - put: app-github-release
        params:
          name: app-resource-version/version
          tag: app-resource-version/version
          globs:
              - output/*zip

      - put: s3
        params:
          file: output/*linux*zip
          acl: public-read

    on_failure:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          Build $BUILD_NAME. *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* failed!
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_success:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          :white_check_mark: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* has a new release.
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

