name: mmm-release

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
#        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        version: latest
        args: --rm-dist

